Repository amk211001/coding-habit-tracker, pull requests merged in 2025-10, with the labels that each got.

#2 add habbit with a category feild
  src/App.js
Labels: hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#24 Habit adding funcationality
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#26 added category options
  src/App.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#27 implement habbit filter based on category
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#32 Impemented logic to automatically award achievements based on habit p…
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted, good-first-issue

#33 Added achievements as badges on habit cards
  package-lock.json
  package.json
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#36 Calculate and display average daily completions implementation
  src/App.css
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#39 Added new Features
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#42 Add PropTypes to HabitForm for type checking
  src/components/HabitForm.js
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted
